{% set name = "gtkwave" %}
{% set version = "3.3.110" %}
{% set build = 0 %}
{% set sha256 = "e4c6edd53a59cf43188707df264b61dead9cf747502bcf80f62a2799c6ab54c3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://gtkwave.sourceforge.net/gtkwave-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - tk
    - gperf
    - gtk2
    - xz
  run:
    - zlib
    - gtk2
    - libglib
    - pango
    - gdk-pixbuf

test:
  commands:
    - gtkwave --help

about:
  home: http://gtkwave.sourceforge.net/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.TXT
  summary: GTKWave is a fully featured GTK+ based wave viewer
  dev_url: https://sourceforge.net/projects/gtkwave

extra:
  recipe-maintainers:
    - davidbrochart
